services:

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    ports:
        - 80:80
        - 81:81
    volumes:
        - ./nginx/nginx_data:/data
        - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
        - seafile-net
        - media-net
        - monitoring-net
        - assistant-net
        - servers-net
        - deposito-net
    extra_hosts:
        - "host.docker.internal:host-gateway"
    restart: unless-stopped

  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=300

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:alpine
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=${PORTAINER_HOSTNAME}
      - VIRTUAL_PORT=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    networks:
      - monitoring-net

  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "4 0 * * 4" --cleanup

networks:

  deposito-net:
    external: true

  seafile-net:
    external: true
    # internal: true

  monitoring-net:
    external: true
    internal: true

  media-net:
    external: true
    internal: true

  assistant-net:
    external: true

  servers-net:
    external: true

include:
  - monitor/docker-compose.yaml

  - torrent/docker-compose.yaml

  - home-assistant/docker-compose.yaml

  - seafile/docker-compose.yaml

  - jellyfin/docker-compose.yaml

  - audiobookshelf/docker-compose.yaml

  - servers/docker-compose.yaml

#  - deposito/docker-compose.yaml
