services:

  home-assistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    expose:
      - 8123
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    networks:
      - assistant-net
    privileged: true
#    network_mode: host
