services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - monitoring-net
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    user: "1000"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitoring-net
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_LOG_LEVEL=warn
      - GF_LIVE_ENABLED=false
      - GF_LOG_FILTERS=context:error
    user: "1000"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    expose:
      - 9100
    networks:
      - monitoring-net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /var/lib/node_exporter/textfile_collector:/var/lib/node_exporter/textfile_collector:ro
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.textfile.directory=/var/lib/node_exporter/textfile_collector'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|etc)($$|/)|^/host/(sys|proc|dev|etc)($$|/)'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.0
    container_name: cadvisor
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - monitoring-net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    expose:
      - 3100
    restart: unless-stopped
    networks:
      - monitoring-net
    volumes:
      - ./loki/loki.yml:/etc/loki/local-config.yaml
      - ./loki/data:/tmp/loki
    user: "1000"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    restart: unless-stopped
    networks:
      - monitoring-net
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
