services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - monitoring-net
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/prometheus_data:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    user: "1000"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - monitoring-net
    volumes:
      - ./grafana:/var/lib/grafana
    user: "1000"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    expose:
      - 9100
    networks:
      - monitoring-net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
#      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|etc)($$|/)|^/host/(sys|proc|dev|etc)($$|/)'
#    logging:
#      driver: loki
#      options:
#        loki-url: "http://loki:3100/loki/api/v1/push"
#        loki-external-labels: "container_name={{.Name}},job=dockerlogs"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    expose:
      - 8080
    restart: unless-stopped
    networks:
      - monitoring-net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


#  loki:
#    image: grafana/loki:latest
#    container_name: loki
#    volumes:
#      - ./loki/config.yaml:/etc/loki/config.yaml:ro
#      - data_loki:/loki:rw
#    ports:
#      - "3100:3100"
#    command: -config.file=/etc/loki/config.yaml
#    restart: unless-stopped
#    networks:
#     - monitoring-net
#    logging:
#      driver: loki
#      options:
#        loki-url: "http://loki:3100/loki/api/v1/push"
#        loki-external-labels: "container_name={{.Name}},job=dockerlogs"
#
#
#  promtail:
#    image: grafana/promtail:latest
#    container_name: promtail
#    volumes:
#      - /var/log:/var/log
#    command: -config.file=/etc/promtail/config.yml
#    networks:
#      - monitoring-net

volumes:
  data_loki:
    driver: local
