
# Loads default set of integrations. Do not remove.
default_config:

automation: !include automations.yaml
script: !include scripts.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.22.0.0/16

# Watch group
group:
  garmin:
    name: Garmin
    entities:
      - script.all_lights_off
      - script.all_lights_on
      - script.corridor_lights_toggle
      - script.casual
      - script.kitchen_lights_toggle
      - script.stop_cleaning
      - script.start_cleaning

aio_energy_management:
  cheapest_hours:
    - nordpool_entity: sensor.nordpool_kwh_ee_eur_3_10_022
      unique_id: my_cheapest_hours_sensor
      name: My Cheapest Hours
      first_hour: 21
      last_hour: 20
      starting_today: true
      number_of_hours: 2
      sequential: False
      failsafe_starting_hour: 22
    - nordpool_entity: sensor.nordpool_kwh_ee_eur_3_10_022
      unique_id: my_expensive_hours_sensor
      name: My Expensive Hours
      first_hour: 20
      last_hour: 16
      starting_today: true
      number_of_hours: 2
      sequential: False
      inversed: true

  calendar:
    name: Energy Management Calendar
    unique_id: energy_management_calendar
